In [1]:
[2,3,4]*2 # Works like list.extends

[2, 3, 4, 2, 3, 4]

In [2]:
[2,3,4]+2

TypeError: can only concatenate list (not "int") to list

# Numpy For the Solution.
## Numpy ndarray (n dimension array)

In [1]:
import numpy as np
fixed_salary=[100,200,300]
variable_salary=[10,20,30]
print(fixed_salary+variable_salary) # Works like list.extends
print("Above is not what we require, we need to add 0th position value in fixed_salary and variable_salary and 1st and so on as given below")
fixed=np.array(fixed_salary)
variable=np.array(variable_salary)
total=fixed+variable
print(total)

[100, 200, 300, 10, 20, 30]
Above is not what we require, we need to add 0th position value in fixed_salary and variable_salary and 1st and so on as given below
[110 220 330]


In [14]:
fixed=np.array([10,20,30])
fixed=fixed+10
print(fixed)
print(fixed>20)
print(fixed[fixed>20]) # Behaving like a filter and is called Boolean Indexing
print(fixed[fixed>20][1])

[20 30 40]
[False  True  True]
[30 40]
40


In [25]:
ps=range(10)
ps=np.array(ps)
ps_eve=ps[ps%2==0]
print(ps_eve**2)
print(ps[ps%2==0]**2)
print(ps[ps%2!=0]**2)
print(ps_eve)

[ 0  4 16 36 64]
[ 0  4 16 36 64]
[ 1  9 25 49 81]
[0 2 4 6 8]


In [20]:
np.array([True,1,3])+np.array([0,1,False]) # Trues is Treated as 1 and False as 0

array([1, 2, 3])

In [23]:
np.array(["1",1,3])+np.array([0,1,False]) # Mixed data type with wont work

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [24]:
np.array([1,2,3])*2

array([2, 4, 6])

In [27]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)
print(np_baseball)

print(np_baseball[1][0])
print(np_baseball[1,0])

<class 'numpy.ndarray'>
(4, 2)
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
215.0
215.0


In [30]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [59]:
arrayvalue=np.array([[1,2,0],
          [3,4,0],
          [5,6,0]
          ])
type(arrayvalue)
print(arrayvalue)
print(arrayvalue.shape)
print(arrayvalue.size)
print(arrayvalue.dtype)
print(arrayvalue.ndim)

[[1 2 0]
 [3 4 0]
 [5 6 0]]
(3, 3)
9
int64
2


# arrange

In [45]:
import numpy as np
print("A series of numbers:", np.arange(2,10,1))
print("A series of numbers:", np.arange(10,1,-1))
print("A series of numbers:", np.arange(10,-10,-1))

A series of numbers: [2 3 4 5 6 7 8 9]
A series of numbers: [10  9  8  7  6  5  4  3  2]
A series of numbers: [10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [51]:
print("21 linearly spaced numbers between 1 and 5")
print(np.linspace(1,5,21,retstep=True))

21 linearly spaced numbers between 1 and 5
(array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ]), np.float64(0.2))


In [62]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
ones=np.ones((3,2))
print(ones)
ones=np.ones((2,3,4))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [66]:
np.zeros_like(ones)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
np.logspace(2.0,3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

# Reshaping

In [72]:
arrangement=np.arange(4)
print(arrangement)
print(arrangement[::-1])
print(arrangement.reshape((2,2)))

[0 1 2 3]
[3 2 1 0]
[[0 1]
 [2 3]]


# RandInt

In [79]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape((2,3,5))
c = a.reshape((6,5))
print(a)
print(b)
print(c)
print(b[0,2,3])
print(b.ndim)
print(b.shape)

[42 30 45 85 16 23 44 80 29 98 45 88 87  9 97 98 94 86  2 31 76  5 73 85
 87  8 22 83 54 50]
[[[42 30 45 85 16]
  [23 44 80 29 98]
  [45 88 87  9 97]]

 [[98 94 86  2 31]
  [76  5 73 85 87]
  [ 8 22 83 54 50]]]
[[42 30 45 85 16]
 [23 44 80 29 98]
 [45 88 87  9 97]
 [98 94 86  2 31]
 [76  5 73 85 87]
 [ 8 22 83 54 50]]
9
3
(2, 3, 5)


In [83]:
from numpy.random import randint as ri
print(ri(1,100,10))
print(np.sort(ri(1,100,10),kind='mergesort'))


[11 31 38 50 18 21 53 19 16 89]
[11 21 28 39 44 48 65 66 79 99]


In [97]:
M=ri(1,100,25).reshape(5,5)
print(M)
print(np.sort(M,kind='mergesort'))
print(np.sort(M,axis=0,kind='mergesort'))
print(M.max())
print(M.argmax())
print(M[0:3,1:3])
print(M[3:5,3:5])

[[53 74 27 76 72]
 [10 89 38 77 68]
 [23 43 36 66 37]
 [16 37 36  5 30]
 [67  6 14 68 74]]
[[27 53 72 74 76]
 [10 38 68 77 89]
 [23 36 37 43 66]
 [ 5 16 30 36 37]
 [ 6 14 67 68 74]]
[[10  6 14  5 30]
 [16 37 27 66 37]
 [23 43 36 68 68]
 [53 74 36 76 72]
 [67 89 38 77 74]]
89
6
[[74 27]
 [89 38]
 [43 36]]
[[ 5 30]
 [68 74]]


In [111]:
M=ri(1,100,24).reshape(2,3,4)
print(M)
sliced_M = M[0:, 0:2, 0:2]

print("\nSliced array (shape: {}):\n".format(sliced_M.shape))
print(sliced_M)
print(M[[0,0,0],[1,1,1]])

[[[62  5 14 62]
  [78 14 39 77]
  [96 31 89  2]]

 [[43 88 90 31]
  [68 81 44 38]
  [ 1 77 48 61]]]

Sliced array (shape: (2, 2, 2)):

[[[62  5]
  [78 14]]

 [[43 88]
  [68 81]]]
[[78 14 39 77]
 [78 14 39 77]
 [78 14 39 77]]


In [112]:
import numpy as np
from numpy.random import randint as ri
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

Matrix of random 2-digit numbers
--------------------------------
 [[25 41 45 88 48]
 [94 95 19 58 11]
 [88 79 31 25 61]]


In [113]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[58 11]
 [25 61]]


In [118]:
import numpy as np
from numpy.random import randint as ri
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

Matrix of random 2-digit numbers
--------------------------------
 [[98 87 54 24 87]
 [86 39 79 64 53]
 [91 74 87 91 44]]


In [120]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3,4]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[87 24 87]
 [39 64 53]]


# Pandas

In [6]:
import pandas as pd
data= pd.DataFrame([list("abcde"),
 [1,2,3,4,5],
 list("qwert"),
 [6,7,8,9,10]],
index=list("asdf"),
columns=list("mnxyz")
)
data

m  n  x  y   z
a  a  b  c  d   e
s  1  2  3  4   5
d  q  w  e  r   t
f  6  7  8  9  10

In [7]:
d={"k":[12,23,34],"k2":[17,34,55]}
pd.DataFrame(d)

k  k2
0  12  17
1  23  34
2  34  55

In [8]:
d={"k":[12,23,34],"k2":17}
pd.DataFrame(d)

k  k2
0  12  17
1  23  17
2  34  17

In [9]:
a=['abc','xyz','pqr']
b=['q','w','r']
d={"k":a,"k2":b}
pd.DataFrame(d)

k k2
0  abc  q
1  xyz  w
2  pqr  r

In [32]:
a=['abc','abc','pqr']
b=['q',None,'r']
d={"k":a,"k2":b}
df=pd.DataFrame(d)
pd

<module 'pandas' from 'C:\\Users\\Ankur Goyal\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\pandas\\__init__.py'>

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   k       3 non-null      object
 1   k2      2 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes


In [33]:
df.describe()

k k2
count     3  2
unique    2  2
top     abc  q
freq      2  1

In [25]:
df.columns

Index(['k', 'k2'], dtype='object')

In [78]:
df.columns=["Key1","Key2"]

In [36]:
df

Key1  Key2
0  abc     q
1  abc  None
2  pqr     r

In [46]:
df.rename(columns={"Key2":"Names"},inplace=True)

In [79]:
df

Key1  Key2
a  abc     q
s  abc  None
d  pqr     r

In [30]:
df["Key1"] # Print single column as Series

0    abc
1    abc
2    pqr
Name: Key1, dtype: object

In [40]:
df[["Key1"]] #Print as DataFrame

Key1
0  abc
1  abc
2  pqr

In [48]:
df[0:1]

Key1 Names
0  abc     q

In [49]:
df[0:]

Key1 Names
0  abc     q
1  abc  None
2  pqr     r

In [50]:
df[2:]

Key1 Names
2  pqr     r

In [51]:
df[:2]

Key1 Names
0  abc     q
1  abc  None

In [94]:
df["a":"d"][["Key1","Key2"]]

Key1  Key2
a  abc     q
s  abc  None
d  pqr     r

In [77]:
df["Key1":"Names"]

KeyError: 'Key1'

In [55]:
df.index=list("asd")

In [56]:
df

Key1 Names
a  abc     q
s  abc  None
d  pqr     r

In [66]:
df.iloc[[0]]

Key1 Names
a  abc     q

In [64]:
df.loc[['a']]

Key1 Names
a  abc     q

In [68]:
df.loc[['a'],["Names"]]

Names
a     q

In [69]:
df.loc[['a'],["Key1","Names"]]

Key1 Names
a  abc     q

In [71]:
df.loc[['a','d'],["Key1","Names"]]

Key1 Names
a  abc     q
d  pqr     r

In [75]:
df.loc[:"d",["Key1","Names"]]

Key1 Names
a  abc     q
s  abc  None
d  pqr     r

In [76]:
df.loc[:"s",["Key1","Names"]]

Key1 Names
a  abc     q
s  abc  None

In [101]:
df.iloc[:2,0:]

Key1  Key2
a  abc     q
s  abc  None

In [103]:
df.iloc[[0,1],[0]]

Key1
a  abc
s  abc

In [105]:
df.iloc[[1,0],[0,1]]

Key1  Key2
s  abc  None
a  abc     q

In [2]:
import numpy as np
arrayvalue=np.array([[1,2,0],
          [3,4,0],
          [5,6,0]
          ])

In [4]:
arrayvalue[arrayvalue>2]

array([3, 4, 5, 6])

In [1]:
import numpy as np

# --- 1. Create the 3D base array ---
# Shape (2, 3, 4): 2 layers, 3 rows, 4 columns
base_3d_array = np.arange(2, 26).reshape((2, 3, 4)) # Start from 2 to avoid 0/1 complexities initially

print("Base 3D Array (shape {}):".format(base_3d_array.shape))
print(base_3d_array)
print("-" * 40)

# --- 2. Create the 2D exponent array ---
# Shape (3, 4) - must match the last two dimensions of the base array
# Using small integers for exponents for clarity
exponent_2d_array = np.array([
    [0, 1, 2, 1],
    [1, 0, 1, 2],
    [2, 1, 0, 1]
])

print("Exponent 2D Array (shape {}):".format(exponent_2d_array.shape))
print(exponent_2d_array)
print("-" * 40)

# --- 3. Perform the power operation using broadcasting ---

# Explanation:
# base_3d_array[i, j, k] will be raised to the power exponent_2d_array[j, k]
# The exponent array is effectively broadcast across the first dimension (axis 0) of the base array.

# Using numpy.power()
result_power_func = np.power(base_3d_array, exponent_2d_array)

# Using the ** operator (equivalent)
result_power_op = base_3d_array ** exponent_2d_array

print("\nResult of 3D_array ** 2D_exponent_array (using np.power):")
# Note: Any number to the power of 0 is 1. Any number to the power of 1 is itself.
print(result_power_func)

print("\nResult of 3D_array ** 2D_exponent_array (using ** operator):")
print(result_power_op)

# Verify they are the same
assert np.array_equal(result_power_func, result_power_op)
print("\nResults from np.power and ** are identical.")
print("-" * 40)

# --- Verification of one element ---
# Let's check base_3d_array[1, 1, 2] ** exponent_2d_array[1, 2]
base_element = base_3d_array[1, 1, 2] # This is 18
exponent_element = exponent_2d_array[1, 2] # This is 1
expected_result = base_element ** exponent_element # 18 ** 1 = 18
actual_result = result_power_op[1, 1, 2]
print(f"\nVerification:")
print(f"Base element at [1, 1, 2]: {base_element}")
print(f"Exponent element at [1, 2]: {exponent_element}")
print(f"Expected result ({base_element}**{exponent_element}): {expected_result}")
print(f"Actual result in output array at [1, 1, 2]: {actual_result}")
assert expected_result == actual_result

# Let's check base_3d_array[0, 2, 0] ** exponent_2d_array[2, 0]
base_element = base_3d_array[0, 2, 0] # This is 10
exponent_element = exponent_2d_array[2, 0] # This is 2
expected_result = base_element ** exponent_element # 10 ** 2 = 100
actual_result = result_power_op[0, 2, 0]
print(f"\nAnother Verification:")
print(f"Base element at [0, 2, 0]: {base_element}")
print(f"Exponent element at [2, 0]: {exponent_element}")
print(f"Expected result ({base_element}**{exponent_element}): {expected_result}")
print(f"Actual result in output array at [0, 2, 0]: {actual_result}")
assert expected_result == actual_result

Base 3D Array (shape (2, 3, 4)):
[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]]]
----------------------------------------
Exponent 2D Array (shape (3, 4)):
[[0 1 2 1]
 [1 0 1 2]
 [2 1 0 1]]
----------------------------------------

Result of 3D_array ** 2D_exponent_array (using np.power):
[[[  1   3  16   5]
  [  6   1   8  81]
  [100  11   1  13]]

 [[  1  15 256  17]
  [ 18   1  20 441]
  [484  23   1  25]]]

Result of 3D_array ** 2D_exponent_array (using ** operator):
[[[  1   3  16   5]
  [  6   1   8  81]
  [100  11   1  13]]

 [[  1  15 256  17]
  [ 18   1  20 441]
  [484  23   1  25]]]

Results from np.power and ** are identical.
----------------------------------------

Verification:
Base element at [1, 1, 2]: 20
Exponent element at [1, 2]: 1
Expected result (20**1): 20
Actual result in output array at [1, 1, 2]: 20

Another Verification:
Base element at [0, 2, 0]: 10
Exponent element at [2, 0]: 2
Expected result (10**2): 100
