In [1]:
[2,3,4]*2

[2, 3, 4, 2, 3, 4]

# Numpy

### Limitation of List

In [2]:
[1,2,3]+4  # ELEMENT WISE OPERATION EXPECTED !!!!

TypeError: can only concatenate list (not "int") to list

In [4]:
l=[2,3,4,5]
l2=[6,5,4,3]

In [5]:
l+l2

[2, 3, 4, 5, 6, 5, 4, 3]

In [ ]:
# Try below operations

* l-l2
* l+l2**
* l/l2
* l*l2  
* l2-10
* l2+10
* l2x*10 **
* l2/10

In [6]:
l2>5 # logical gate do not work 

TypeError: '>' not supported between instances of 'list' and 'int'

In [ ]:
# l*2

In [ ]:
# Try 
# l +-*/ 5
#l2 +-*/l
# Tell which worked 

### element wise operation

In [ ]:
l=[2,3,4,5]


In [7]:
# to do this 
lst=[]# to append
print(l)
for i in l:
    print(i**2)
    lst.append(i**2)
print(lst)

[2, 3, 4, 5]
4
9
16
25
[4, 9, 16, 25]


* How to add lst1+lst2 element wise
* lst1=[2,3,5],lst2=[4,5,6]

In [ ]:
list1,list2=[2,3,5],[4,5,6]

In [ ]:
print(f"list1=>{list1},list2=>{list2}")

In [ ]:
#ADDING 
list3=[]
for i in range(len(list1)):
    list3.append(list1[i] + list2[i])
print(list3)

In [ ]:
l*2 # just print the list twice

In [ ]:
l1=[6,7,8,9]

In [ ]:
l+l1

In [ ]:
l*l1

In [ ]:
l-l1

In [ ]:
l/l1

### We dont have element wise operations in list

#### Example

In [8]:
fixed_salary = [100,200,300]
variable_salary = [10,20,30]
total_salary = fixed_salary + variable_salary
print(total_salary)

[100, 200, 300, 10, 20, 30]


In [ ]:
type(fixed_salary)

## Numpy For The Solution

In [9]:
import numpy as np    

fixed = np.array(fixed_salary)  #type conversion
variable = np.array(variable_salary)
total = fixed + variable   # both has to be of the same size
print(total)

[110 220 330]


In [11]:
np.array([2,3,4])+np.array([2,3,4,5,6])

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [ ]:
# Try all this with array
# l +-*/ 5
#l2 +-*/l
# Tell which worked 

In [12]:
type(fixed)

numpy.ndarray

In [13]:
fixed

array([100, 200, 300])

In [14]:
variable

array([10, 20, 30])

In [16]:
type(total)

numpy.ndarray

In [17]:
total

array([110, 220, 330])

In [18]:
#Broadcasting  | element wise
total+10

array([120, 230, 340])

In [19]:
#Broadcasting
total>200

array([False,  True,  True])

In [20]:
#Boolean Indexing
total[total>200]

array([220, 330])

In [21]:
total[total>200][1]

330

filter all even value and find the sq of each

In [22]:
ps=[2,3,4,5,6,7,8,9,10]
ps=np.array(ps)
ps_eve=ps[ps%2==0]
print(ps_eve)
print(ps_eve**2)

[ 2  4  6  8 10]
[  4  16  36  64 100]


In [33]:
ps%2==0

array([False,  True, False,  True])

In [34]:
ps[ps%2==0]

array([2, 4])

In [32]:
ps=[1,2,3,4]
ps=np.array(ps)
print(ps)
ps[ps%2==0]**2

[1 2 3 4]


array([ 4, 16])

In [35]:
ps[ps%2!=0]**2 #odd

array([1, 9])

In [24]:
# single line
ps=[2,3,4,5,6,7,8,9,10]
ps=np.array(ps)

print(ps)
ps[ps%2==0]**2

[ 2  3  4  5  6  7  8  9 10]


array([  4,  16,  36,  64, 100])

* Numpy is great for doing vector arithmetic.
* If you compare its functionality with regular Python lists, however, some things have changed.
* First of all, numpy arrays cannot contain elements with different types.
* The typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

In [25]:
"a"+6

TypeError: can only concatenate str (not "int") to str

In [27]:
np.array(["a", 1, 2,'b'])

array(['a', '1', '2', 'b'], dtype='<U11')

In [28]:
np.array(["a", 1, 2,'b'])*3

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [29]:
np.array([ 1, 2])*3

array([3, 6])

In [30]:
np.array(["True", 1, 2]) +2

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [31]:
np.array([True, 1, 2]) + np.array([3, 4, False]) #True =1 , False=0

array([4, 5, 2])

In [36]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)
print(np_baseball)

<class 'numpy.ndarray'>
(4, 2)
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [37]:
print(np_baseball[1][0])
print(np_baseball[1,0])     # both do the same thing 

215.0
215.0


In [ ]:
#Upcasting:

In [38]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [ ]:
#two dimensions

In [39]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

## arange

In [40]:
print("A series of numbers:",np.arange(5,16))
# A series of numbers from low to high

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]


In [41]:
print("Numbers spaced apart by 2:",np.arange(0,11,2)) 
# Numbers spaced apart by 2

Numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [42]:
import numpy as np
np.arange(10,1,-1) 

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [49]:
np.__version__


'1.26.4'

In [43]:
np.arange(10,-10,-1) 

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5, -6,
       -7, -8, -9])

In [44]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------")
print(np.linspace(1,5,21))#1-lower 5 -higher 21 number of element

21 linearly spaced numbers between 1 and 5
--------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


In [45]:
print(np.linspace(1,5,21,retstep=True))#1-lower 5 -higher 21 number of element

(array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ]), 0.2)


In [46]:
#import numpy as np
np.linspace(2.0, 3.0, num=9, retstep=True) # give u the step size 

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [50]:
import numpy as np
my_mat= [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)

print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim)
#ndim gives the dimensison, 2 for a matrix, 1 for a vector

print("Size of this matrix: ", mat.size)
#size gives the total number of elements

print("Shape of this matrix: ", mat.shape)
#shape gives the number of elements along each axes (dimension)

print("Data type of this matrix: ", mat.dtype)
#dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix:  2
Size of this matrix:  9
Shape of this matrix:  (3, 3)
Data type of this matrix:  int32


# Matrix creation

In [51]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [52]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [53]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [54]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [55]:
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [56]:
a=[2,3,4]
np.zeros_like(a)

array([0, 0, 0])

In [57]:
b=[[2,3,4],[4,5,6]]
np.zeros_like(b)

array([[0, 0, 0],
       [0, 0, 0]])

In [58]:
b=[[2,3,4],[4,5,6]]
np.ones_like(b)

array([[1, 1, 1],
       [1, 1, 1]])

In [60]:
b=np.array([[2,3,4],[4,5,6]])
print("shape",b.shape)
np.ones(b.shape)  # same can be done by this !!!

shape (2, 3)


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Return numbers spaced evenly on a log scale.

In [61]:
np.logspace(2.0, 3.0, num=4)  # default base base=10.0

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [62]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [63]:
import numpy as np
np.logspace( 1,4) # num =50 default

array([   10.        ,    11.51395399,    13.25711366,    15.26417967,
          17.57510625,    20.23589648,    23.29951811,    26.82695795,
          30.88843596,    35.56480306,    40.94915062,    47.14866363,
          54.28675439,    62.50551925,    71.9685673 ,    82.86427729,
          95.40954763,   109.8541142 ,   126.48552169,   145.63484775,
         167.68329368,   193.06977289,   222.29964825,   255.95479227,
         294.70517026,   339.32217719,   390.69399371,   449.8432669 ,
         517.94746792,   596.36233166,   686.648845  ,   790.60432109,
         910.29817799,  1048.11313415,  1206.79264064,  1389.49549437,
        1599.85871961,  1842.06996933,  2120.95088792,  2442.05309455,
        2811.76869797,  3237.45754282,  3727.59372031,  4291.93426013,
        4941.71336132,  5689.86602902,  6551.2855686 ,  7543.12006335,
        8685.11373751, 10000.        ])

# Reshaping

In [2]:
import numpy as np

In [64]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
x= np.arange(9).reshape((3,3)) 
#reshape value is equals the multiplication of row n col to number of element

In [66]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#  RandInt  

In [67]:
from numpy.random import randint as ri  # random + int
a = ri(1,100,30) # bw 1 to 100 ---- 30 values will be given randomly
b = a.reshape(2,3,5) # 2 matrix with 3 rows and 5 col
c = a.reshape(6,5)
#import np.random.randint as ri

In [68]:
## eg
ri(1.5,98.7,30) # only int as output

array([75, 85, 95, 47, 76, 87,  1, 88, 33,  2, 91, 14, 86, 34, 22, 28, 85,
        1, 51, 87, 27, 56, 17, 97, 43, 26, 54, 61, 16, 18])

In [69]:
a

array([23, 68, 89, 15, 11, 31, 63, 33,  6, 53, 66, 32, 56,  4, 54, 74, 52,
       12, 48, 84, 83, 33,  3, 50, 68, 99, 23, 94, 48, 79])

In [70]:
b

array([[[23, 68, 89, 15, 11],
        [31, 63, 33,  6, 53],
        [66, 32, 56,  4, 54]],

       [[74, 52, 12, 48, 84],
        [83, 33,  3, 50, 68],
        [99, 23, 94, 48, 79]]])

In [73]:
b.ndim

3

In [ ]:
c

In [72]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [74]:
b[1]

array([[74, 52, 12, 48, 84],
       [83, 33,  3, 50, 68],
       [99, 23, 94, 48, 79]])

In [75]:
b[1][2]

array([99, 23, 94, 48, 79])

In [76]:
b[1][2][1] #Indexing  b[0,1,2]

23

In [77]:
b[1,2,1]

23

In [ ]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


In [2]:
import numpy as np
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))#  , kind='mergesort')

'-'*50

NameError: name 'ri' is not defined

In [78]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort'))
# Default axis =-1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[55 88 21 45 80]
 [16 95 12 16 27]
 [47 40 57 66 19]
 [21 12 53  2 93]
 [91  6 17 92 16]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[21 45 55 80 88]
 [12 16 16 27 95]
 [19 40 47 57 66]
 [ 2 12 21 53 93]
 [ 6 16 17 91 92]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[16  6 12  2 16]
 [21 12 17 16 19]
 [47 40 21 45 27]
 [55 88 53 66 80]
 [91 95 57 92 93]]


In [81]:
a

array([23, 68, 89, 15, 11, 31, 63, 33,  6, 53, 66, 32, 56,  4, 54, 74, 52,
       12, 48, 84, 83, 33,  3, 50, 68, 99, 23, 94, 48, 79])

In [82]:
b

array([[[23, 68, 89, 15, 11],
        [31, 63, 33,  6, 53],
        [66, 32, 56,  4, 54]],

       [[74, 52, 12, 48, 84],
        [83, 33,  3, 50, 68],
        [99, 23, 94, 48, 79]]])

In [79]:
print("Max of a:", a.max())
print("Max of b:", b.max())


Max of a: 99
Max of b: 99


In [80]:
print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

Max of a location: 25
Max of b location: 25
Max of c location: 25


# Indexing and slicing

In [1]:
arr = np.arange(10,21)
print("Array:",arr)

NameError: name 'np' is not defined

In [84]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 17


In [85]:
print("Elements from 3rd to 5th index are:", arr[3:6])


Elements from 3rd to 5th index are: [13 14 15]


In [86]:
print("Elements up to 4th index are:", arr[:4])


Elements up to 4th index are: [10 11 12 13]


In [87]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [10]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset
print("Elements at 2nd, 4th, and 9th index are:", arr[2:4])

Elements at 2nd, 4th, and 9th index are: [12 14 19]
Elements at 2nd, 4th, and 9th index are: [12 13]


# SUB MATRIX

In [89]:
import numpy as np
from numpy.random import randint as ri
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

Matrix of random 2-digit numbers
--------------------------------
 [[82 44 57 18 56]
 [84 68 40 46 82]
 [48 65 65 58 93]]


In [91]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])     



Double bracket indexing
------------------------
Element in row index 1 and column index 2: 40


In [92]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 40

Row or column extract
----------------------


In [93]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [48 65 65 58 93]
Entire column at index 3: [18 46 58]


In [95]:
mat

array([[82, 44, 57, 18, 56],
       [84, 68, 40, 46, 82],
       [48, 65, 65, 58, 93]])

In [94]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[46 82]
 [58 93]]


In [96]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[44 18]
 [68 46]]


In [97]:
mat[0:2,[1,3]]

array([[44, 18],
       [68, 46]])

In [104]:
mat

array([[82, 44, 57, 18, 56],
       [84, 68, 40, 46, 82],
       [48, 65, 65, 58, 93]])

In [103]:
mat[[0,2],[1,4]]

array([44, 93])

In [105]:
mat[[1,2],]

array([[84, 68, 40, 46, 82],
       [48, 65, 65, 58, 93]])

In [106]:
mat[[1,2],[1,3]]  # row,col

array([68, 58])

In [100]:
mat[[0,2],[[1,4],[1,4]]]   

array([[44, 93],
       [44, 93]])

In [101]:
mat[0:2,[[1,3],[1,4]]]

array([[[44, 18],
        [44, 56]],

       [[68, 46],
        [68, 82]]])

# Subseting

In [ ]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


In [ ]:
print ("Elements greater than 50\n", mat[mat>50])

# Slicing

In [ ]:
import numpy as np
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


In [ ]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")

In [ ]:
mat_slice[0,0] = 1000
print (mat_slice)

In [ ]:
mat_slice[0][0] = 2000
mat_slice

# Universal Functions

In [14]:
from numpy.random import randint as ri
import numpy as np
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 4 9]
 [9 4 7]
 [2 5 3]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 9 8]
 [3 7 4]
 [8 6 3]]


In [15]:
print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)



Addition
------------------
 [[11 13 17]
 [12 11 11]
 [10 11  6]]

Multiplication
------------------
 [[24 36 72]
 [27 28 28]
 [16 30  9]]


In [ ]:
print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


In [ ]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


In [ ]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------\n",pow(mat1,0.5))

# Array Math

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n-----------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n-----------------------------------\n",mat2)


In [ ]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


In [ ]:
#Exponential with e (2.71)
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


In [ ]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


# basic stats

In [9]:
from numpy.random import randint as ri
import numpy as np
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[3 5 6]
 [5 2 5]
 [3 9 8]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[6 9 9]
 [1 2 4]
 [4 7 1]]


In [10]:
print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))



Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 46

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [11 16 19]


In [11]:
print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))



Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [14 12 20]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 90  50 216]


In [13]:
print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))



Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [ 24 126  36]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.111111111111111


In [ ]:
print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


In [ ]:
print("\n Variance of all numbers in 1st matrix\n","-"*50,"\n",np.var(mat1))


In [ ]:
print("\n50th percentile of all numbers in the modified matrix\n",
      "-"*60,"\n",np.percentile(mat1,50))


In [ ]:
print("\n90th percentile of all numbers in the modified matrix\n",
      "-"*60,"\n",np.percentile(mat1,90))

In [ ]:
print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))


In [8]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house > 18.5, my_house < 10))

# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11, your_house < 11))

[False  True False  True]
[False False False  True]


In [ ]:
(my_house > 18.5) | (my_house < 10)

In [ ]:
(my_house < 11) & (your_house < 11)

In [ ]:
np_baseball = np.array([[ 74, 180],[ 74, 215],[ 72, 210],[ 75, 205],[ 75, 190],[ 73, 195]])
np_height = np.array([74, 74, 72, 75, 75, 73])

In [ ]:
for x in np_baseball:
    print(x)

In [ ]:
# Import numpy as np
import numpy as np

# For loop over np_height
for x in np_height:
    print(str(x) + " inches")

# For loop over np_baseball
for x in np.nditer(np_baseball): # IMP
    print(str(x))


## Pandas

In [5]:
import pandas as pd

# Build cars DataFrame
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]
dict1 = { 'country':names, 'drives_right':dr, 'cars_per_cap':cpc }
cars = pd.DataFrame(dict1)
print(cars)

# Definition of row_labels
row_labels = ['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG']

# Specify row labels of cars
cars.index = row_labels

# Print cars again
cars

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45


country  drives_right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JAP          Japan         False           588
IN           India         False            18
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

In [6]:
#Renamed
cars.columns = ['Cars Per Capita','Country Name','Drives Right']
cars

Cars Per Capita  Country Name  Drives Right
US    United States          True           809
AUS       Australia         False           731
JAP           Japan         False           588
IN            India         False            18
RU           Russia          True           200
MOR         Morocco          True            70
EG            Egypt          True            45

In [7]:
#Building DataFrames with broadcasting

# Make a string with the value 'PA': state
planet = 'Earth'
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
# Construct a dictionary: data
data = {'Country':names, 'Planet':planet}

# Construct a DataFrame from dictionary data: df
df = pd.DataFrame(data)

# Print the DataFrame
print(df)

         Country Planet
0  United States  Earth
1      Australia  Earth
2          Japan  Earth
3          India  Earth
4         Russia  Earth
5        Morocco  Earth
6          Egypt  Earth


In [ ]:
import pandas as pd

# Build cars DataFrame
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]
dict = { 'country':names, 'drives_right':dr, 'cars_per_cap':cpc }
cars = pd.DataFrame(dict)
print(cars)

# Definition of row_labels
row_labels = ['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG']

# Specify row labels of cars
cars.index = row_labels

# Print cars again
print(cars)

In [ ]:
# Print out country column as Pandas Series
cars['country']

In [ ]:
cars[['country']]

In [ ]:
# Print out DataFrame with country and drives_right columns
cars[['country', 'drives_right']]

In [ ]:
# Print out first 3 observations
print(cars[0:3])

# Print out fourth, fifth and sixth observation
print(cars[3:6])

In [ ]:
# Print out observation for Japan
print(cars.iloc[2])

# Print out observations for Australia and Egypt
print(cars.loc[['AUS', 'EG']])

In [ ]:
# Print out drives_right value of Morocco
print(cars.iloc[5, 2])

# Print sub-DataFrame
print(cars.loc[['RU', 'MOR'], ['country', 'drives_right']])

In [ ]:
# Print out drives_right column as Series
print(cars.iloc[:, 2])

# Print out drives_right column as DataFrame
print(cars.iloc[:, [2]])

# Print out cars_per_cap and drives_right as DataFrame
print(cars.loc[:, ['cars_per_cap', 'drives_right']])

In [ ]:
# Import numpy, you'll need this
import numpy as np

# Create medium: observations with cars_per_cap between 100 and 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 100, cpc < 500)
medium = cars[between]

# Print medium
medium

In [ ]:
cpc > 100

In [ ]:
cpc < 500

In [ ]:
np.logical_and(cpc > 100, cpc < 500)

In [ ]:
# Iterate over rows of cars
for lab, row in cars.iterrows() :
    print(lab)
    print(row)

In [ ]:
# Adapt for loop
for lab, row in cars.iterrows() :
    print(lab + ": " + str(row['cars_per_cap']))

In [ ]:
# Code for loop that adds COUNTRY column
for lab, row in cars.iterrows() :
    cars.loc[lab, "COUNTRY"] = row["country"].upper()
    
# Print cars
print(cars)

In [ ]:
# Use .apply(str.upper)
cars["COUNTRY"] = cars["country"].apply(str.upper)

In [ ]:
cars["name_length"] = cars["country"].apply(len)

### add index

In [ ]:
cars

In [ ]:
import pandas as pd


In [ ]:

a=['abc','xyz','pqr']
b="qwert"
d={"k":a,"k2":b} # with list and a variables Data Frame
df=pd.DataFrame(d) # assigning the Data Frame to a variable 
df   

In [ ]:
pd.get_dummies(df)

In [ ]:
pd.get_dummies(df,drop_first=True)